apiVersion: v1
kind: Service
metadata:
  name: myfastapi-service
spec:
  selector:
    app: myfastapi-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfastapi-app
spec:
  selector:
    matchLabels:
      app: myfastapi-app
  replicas: 5
  template:
    metadata:
      labels:
        app: myfastapi-app
    spec:
      containers:
        - name: myfastapi-app
          image: docker.io/tiagomvieira/fastapibuild
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
